name: [BUG] Bug Report
description: Report a bug or issue with an existing command or prompt
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component Type
      description: What type of component has the bug?
      options:
        - Command (.claude/commands/)
        - Validation Script
        - GitHub Workflow
        - Documentation
        - MCP Configuration
    validations:
      required: true

  - type: input
    id: command-name
    attributes:
      label: Command/Prompt Name
      description: Name of the specific command or prompt with the issue
      placeholder: "e.g., analyze-project, security-audit, test-suite-generation"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe what happened and what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '/example-command parameter'
        2. See error message
        3. Expected behavior was X, but got Y
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages, stack traces, etc.)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      value: |
        - Claude Code Version: 
        - Operating System: 
        - Node.js Version: 
        - Browser (if applicable): 
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have tested this with the latest version of ccprompts
          required: true
        - label: I have provided all the requested information above
          required: true