name: 🚀 Command Proposal
description: Propose a new command for the ccprompts ecosystem
title: "[Command]: "
labels: ["command", "enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## New Command Proposal
        
        Use this template to propose a new command for the ccprompts ecosystem. This helps us understand the command's purpose, implementation, and value to the community.

  - type: input
    id: command-name
    attributes:
      label: Command Name
      description: Proposed command name (use kebab-case)
      placeholder: "e.g., database-migrate, api-security-scan, docker-optimize"
    validations:
      required: true

  - type: dropdown
    id: command-category
    attributes:
      label: Command Category
      description: Which phase/category does this command belong to?
      options:
        - "Phase 1: Category Commands"
        - "Phase 2: Workflow Commands"
        - "Phase 3: Context-Aware Commands"
        - "Phase 4: Utility Commands"
        - "Phase 5: Developer Lifecycle Commands"
        - "Phase 6: Learning Commands"
        - "Specialized Commands"
    validations:
      required: true

  - type: textarea
    id: command-description
    attributes:
      label: Command Description
      description: Brief description of what this command does
      placeholder: "One-line description of the command's primary function"
    validations:
      required: true

  - type: textarea
    id: problem-solved
    attributes:
      label: Problem Solved
      description: What specific development problem does this command address?
      placeholder: "Describe the pain point or inefficiency this command eliminates"
    validations:
      required: true

  - type: textarea
    id: command-usage
    attributes:
      label: Command Usage Syntax
      description: How would developers use this command?
      placeholder: |
        ```bash
        /command-name [parameter1] [parameter2] [optional-parameter]
        ```
    validations:
      required: true

  - type: textarea
    id: parameters
    attributes:
      label: Parameters
      description: Define the command parameters and their valid values
      placeholder: |
        - `parameter1`: `type` | `valid_values` - Description
        - `parameter2`: `enum` | `option1,option2,option3` - Description  
        - `optional-parameter`: `string` - Optional description (default: value)
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide realistic examples of how this command would be used
      placeholder: |
        ```bash
        # Basic usage
        /command-name basic simple
        
        # Advanced usage  
        /command-name advanced complex-option
        
        # Production usage
        /command-name production enterprise-settings
        ```
    validations:
      required: true

  - type: textarea
    id: expected-output
    attributes:
      label: Expected Output/Behavior
      description: What does this command produce or accomplish?
      placeholder: |
        1. Primary deliverable or action
        2. Secondary outputs or side effects
        3. User feedback or reporting
        4. Integration touchpoints
    validations:
      required: true

  - type: dropdown
    id: automation-level
    attributes:
      label: Automation Level
      description: How much automation does this command provide?
      options:
        - "Fully Automated - No user intervention required"
        - "Semi-Automated - Requires some user input/approval"
        - "Interactive - Guides user through manual steps"
        - "Analysis Only - Provides recommendations without changes"
    validations:
      required: true

  - type: dropdown
    id: safety-level
    attributes:
      label: Safety Level
      description: What safety measures does this command need?
      options:
        - "Read-Only - No system changes"
        - "Safe - Reversible changes with backup"
        - "Moderate Risk - Important changes with validation"
        - "High Risk - Requires careful validation and approval"
    validations:
      required: true

  - type: textarea
    id: integration-points
    attributes:
      label: Integration Points
      description: How does this command integrate with existing commands and workflows?
      placeholder: |
        - Works with: /command-a, /command-b
        - Prerequisites: /setup-command
        - Workflow position: After X, before Y
        - Data dependencies: Requires Z configuration
    validations:
      required: true

  - type: textarea
    id: target-audience
    attributes:
      label: Target Audience
      description: Who would primarily use this command?
      placeholder: "e.g., Backend developers, DevOps engineers, Security teams, Frontend developers, All developers"
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Usage Frequency
      description: How often would developers typically use this command?
      options:
        - "Daily - Part of regular development workflow"
        - "Weekly - Regular but not daily usage"  
        - "Monthly - Periodic maintenance or assessment"
        - "As-Needed - Situational or problem-solving usage"
        - "One-Time - Project setup or migration"
    validations:
      required: true

  - type: textarea
    id: learning-objectives
    attributes:
      label: Learning Objectives
      description: What should users learn from using this command?
      placeholder: |
        1. Technical concept or best practice
        2. Tool or technology mastery
        3. Process or methodology understanding
        4. Industry standard or compliance requirement

  - type: textarea
    id: success-metrics
    attributes:
      label: Success Metrics
      description: How would we measure the success and impact of this command?
      placeholder: |
        - Time savings: Reduces X task from Y hours to Z minutes
        - Quality improvement: Reduces errors by X%
        - Productivity boost: Enables Y new capability
        - Learning outcome: Users understand Z concept
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: What tools, dependencies, or prerequisites does this command need?
      placeholder: |
        - External tools: Docker, Kubernetes, specific CLI tools
        - Language/framework requirements: Node.js, Python, etc.
        - API access: GitHub, cloud providers, monitoring services
        - File system access: Read/write permissions needed

  - type: textarea
    id: risk-considerations
    attributes:
      label: Risk Considerations
      description: What risks or potential issues should be considered?
      placeholder: |
        - Data loss risks and mitigation
        - System impact and resource usage
        - Security considerations and access requirements
        - Compatibility issues and version dependencies

  - type: dropdown
    id: implementation-complexity
    attributes:
      label: Implementation Complexity
      description: How complex would this command be to implement?
      options:
        - "Low - Simple script or configuration"
        - "Medium - Moderate development with some integration"
        - "High - Complex logic with multiple dependencies"
        - "Very High - Requires significant research and development"

  - type: checkboxes
    id: implementation-commitment
    attributes:
      label: Implementation Commitment
      description: Are you willing to help implement this command?
      options:
        - label: I can implement the complete command
        - label: I can help with parts of the implementation
        - label: I can provide testing and feedback
        - label: I can contribute domain expertise
        - label: I can help with documentation and examples

  - type: checkboxes
    id: validation-checklist
    attributes:
      label: Validation Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this command doesn't duplicate existing functionality
          required: true
        - label: I have reviewed the command template and understand the requirements
          required: true
        - label: I have provided realistic examples and use cases
          required: true
        - label: I have considered safety and integration requirements
          required: true