name: Branch Naming Convention

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    name: Validate Branch Name
    
    steps:
    - name: Check branch name
      env:
        BRANCH_NAME: ${{ github.head_ref }}
      run: |
        branch_name="$BRANCH_NAME"
        echo "Checking branch name: $branch_name"
        
        # Define allowed patterns
        allowed_patterns=(
          "^feature/[a-z0-9-]+$"
          "^fix/[a-z0-9-]+$" 
          "^docs/[a-z0-9-]+$"
          "^refactor/[a-z0-9-]+$"
          "^test/[a-z0-9-]+$"
          "^chore/[a-z0-9-]+$"
          "^hotfix/[a-z0-9-]+$"
        )
        
        # Check if branch name matches any allowed pattern
        valid=false
        for pattern in "${allowed_patterns[@]}"; do
          if [[ $branch_name =~ $pattern ]]; then
            valid=true
            echo "✅ Branch name '$branch_name' matches pattern: $pattern"
            break
          fi
        done
        
        if [ "$valid" = false ]; then
          echo "❌ Branch name '$branch_name' does not follow naming convention!"
          echo ""
          echo "Allowed patterns:"
          echo "  - feature/description-here"
          echo "  - fix/issue-description"
          echo "  - docs/section-update"
          echo "  - refactor/component-name"
          echo "  - test/test-description"
          echo "  - chore/maintenance-task"
          echo "  - hotfix/urgent-fix"
          echo ""
          echo "Examples:"
          echo "  - feature/analytics-dashboard"
          echo "  - fix/markdown-validation"
          echo "  - docs/readme-improvements"
          echo "  - refactor/mcp-configuration"
          exit 1
        fi
        
        echo "✅ Branch name follows convention!"